import { Inter } from "next/font/google";
import "./globals.css";
import "keen-slider/keen-slider.min.css"

import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import Player from "@/components/track/Player";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Player />
      </body>
    </html>
  );
}
